name: Play Framework Pipeline

on:
  workflow_call:
    inputs:
      jdk:
        required: true
        type: string
      base_image_branch:
        required: false
        type: string
      sbt_build_environment:
        required: false
        type: string
        default: |
          NPM_CONFIG_CACHE=/npm/cache
          NPM_CONFIG_HOME=/npm
          LC_ALL=en_US.UTF-8
          LANG=en_US.UTF-8

env:
  ALMALINUX_VERSION: "9"

jobs:
  build:
    name: sbt tests
    runs-on: [self-hosted, linux, X64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Generate outputs
      shell: bash
      run: |
        IMAGE="java${{ inputs.jdk }}-sbt"

        if [ "${{ inputs.base_image_branch }}" != "" ]; then
          TAG="${ALMALINUX_VERSION}-${{ inputs.base_image_branch }}"
        else
          TAG="${ALMALINUX_VERSION}"
        fi

        echo "##[set-output name=day_of_week;]$(date +%A)"

        echo "##[set-output name=host_ip;]$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)"

        echo "##[set-output name=image;]${IMAGE}:${TAG}"

        SBT_BUILD_ENV=""

        while IFS= read -r ENV_LINE
        do
          if [ "$ENV_LINE" != "" ]; then
            SBT_BUILD_ENV="${SBT_BUILD_ENV} -e ${ENV_LINE}"
          fi
        done < <(printf '%s\n' "${{ inputs.sbt_build_environment }}")

        echo "##[set-output name=sbt_build_environment;]${SBT_BUILD_ENV}"

      id: generate_image

    - name: Run tests
      shell: bash
      run: |
        set -x
        podman run --rm \
          -e TESTCONTAINERS_RYUK_DISABLED=true \
          -e TESTCONTAINERS_HOST_OVERRIDE=${{ steps.generate_image.outputs.host_ip }} \
          -e NODENV_ROOT=/home/builder/.nodenv \
          ${{ steps.generate_image.outputs.sbt_build_environment }} \
          -v $(pwd):$(pwd) \
          -v /run/podman.sock:/run/docker.sock \
          -v /home/github/cache/scala:/cache \
          -v /home/github/cache/npm:/npm/cache \
          -w $(pwd) \
          --entrypoint /bin/bash \
          074509403805.dkr.ecr.eu-west-1.amazonaws.com/${{ steps.generate_image.outputs.image }} \
          -c "if [ -f '.node-version' ]; then nodenv install; fi && sbt -Duser.home=/tmp -Dsbt.log.noformat=true -Dsbt.ivy.home=/cache/.ivy2/ test"

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'target/test-reports/*.xml'

    - name: Upload Vagrant artifact
      shell: bash
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || ( github.event_name == 'schedule' && steps.generate_image.outputs.date == 'Sunday' ) }}
      run: |
        set -x
        podman run --rm \
          ${{ steps.generate_image.outputs.sbt_build_environment }} \
          -e NODENV_ROOT=/home/builder/.nodenv \
          -v $(pwd):$(pwd) \
          -v /home/github/cache/scala:/cache \
          -v /home/github/cache/npm:/npm/cache \
          -w $(pwd) \
          --entrypoint /bin/bash \
          074509403805.dkr.ecr.eu-west-1.amazonaws.com/${{ steps.generate_image.outputs.image }} \
          -c "if [ -f '.node-version' ]; then nodenv install; fi && sbt -Duser.home=/tmp -Dsbt.log.noformat=true -Dsbt.ivy.home=/cache/.ivy2/ assembly publish"

  container_build:
    runs-on: [self-hosted, linux, X64]
    name: Container Build

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate outputs
      shell: bash
      run: |
        if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
          echo "##[set-output name=tags;]074509403805.dkr.ecr.eu-west-1.amazonaws.com/${GITHUB_REPOSITORY:9}:${GITHUB_HEAD_REF} 074509403805.dkr.ecr.eu-west-1.amazonaws.com/${GITHUB_REPOSITORY:9}:${{ github.event.pull_request.head.sha }}"
        else
          echo "##[set-output name=tags;]074509403805.dkr.ecr.eu-west-1.amazonaws.com/${GITHUB_REPOSITORY:9}:${GITHUB_REF:11} 074509403805.dkr.ecr.eu-west-1.amazonaws.com/${GITHUB_REPOSITORY:9}:${GITHUB_SHA}"
        fi

        if [ "${{ inputs.base_image_branch }}" != "" ]; then
          echo "##[set-output name=base_image_tag;]${ALMALINUX_VERSION}-${{ inputs.base_image_branch }}"
        else
          echo "##[set-output name=base_image_tag;]${ALMALINUX_VERSION}"
        fi
      id: generate_tags

    - name: Build
      uses: redhat-actions/buildah-build@v2
      env:
        REGISTRY_AUTH_FILE: /run/user/1001/containers/auth.json
      with:
        containerfiles: deployment/docker/Dockerfile
        context: .
        build-args: |
          BASE_TAG=${{ steps.generate_tags.outputs.base_image_tag }}
        extra-args: |
          -v=/home/github/cache/scala:/cache:shared,rw
          --ulimit=nofile=262144:262144
        tags: ${{ steps.generate_tags.outputs.tags }}

    - name: Push to ECR
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: ${{ steps.generate_tags.outputs.tags }}
